# Generated by Django 5.2.5 on 2025-08-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoiloitem',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
